### PR TITLE
Fix typed data serialization

### LINKED ISSUE #204: Incorrect encoding of StarknetTypedData
### What happened

When the following typed data is decoded to `StarknetTypedData`, when that type is encoded again to JSON, the `type` field for the `merkeltree` type is missing. See the `Allowed Methods` field in `Session` in the JSON below.

From looking at the code it looks like the same problem exists for `enum` types, although I don't have an example of that.

The same bug exists in the Java SDK: https://github.com/software-mansion/starknet-jvm/issues/498

```json
{
  "types": {
    "StarknetDomain": [
      {
        "name": "name",
        "type": "shortstring"
      },
      {
        "name": "version",
        "type": "shortstring"
      },
      {
        "name": "chainId",
        "type": "shortstring"
      },
      {
        "name": "revision",
        "type": "shortstring"
      }
    ],
    "Allowed Method": [
      {
        "name": "Contract Address",
        "type": "ContractAddress"
      },
      {
        "name": "selector",
        "type": "selector"
      }
    ],
    "Session": [
      {
        "name": "Expires At",
        "type": "timestamp"
      },
      {
        "name": "Allowed Methods",
        "type": "merkletree",
        "contains": "Allowed Method"
      },
      {
        "name": "Metadata",
        "type": "string"
      },
      {
        "name": "Session Key",
        "type": "felt"
      }
    ]
  },
  "primaryType": "Session",
  "domain": {
    "name": "SessionAccount.session",
    "version": "0x31",
    "chainId": "0x534e5f5345504f4c4941",
    "revision": "1"
  },
  "message": {
    "Expires At": 1720704208,
    "Allowed Methods": [
      {
        "Contract Address": "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
        "selector": "transfer"
      }
    ],
    "Metadata": "{\"projectID\":\"test-dapp\",\"txFees\":[{\"tokenAddress\":\"0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7\",\"maxAmount\":\"100000000000000000\"}]}",
    "Session Key": "0x3f94fb0d79cba8507a8775dc4cd4328f91ba33d1a32cb54c8c28eef0e258fa3"
  }
}
```

### Stack trace

N/A

### Steps to reproduce

1. Decode the JSON provided above to a `StarknetTypedData` object.
2. Encode the object from 1. back to JSON. 
3. The `type` field is missing for the `Allowed Methods` `merkletree` type.

### SDK Version

0.10.1

### Language version

Swift 5.10

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

### PR DESCRIPTION
**Pull request by franciszekjob**
## Describe your changes

Fix encoding of `u128`, `i128` and `timestamp`

**Before**: When typed data was decoded to `StarknetTypedData` and then encoded again to JSON,  `u128`, `i128` and `timestamp` were encoded as hex values
**Now**: They are encoded in line with [SNIP-12](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md)

## Linked issues

Closes #204, #205, #206 

## Breaking changes

- [ ] This issue contains breaking changes

### CODE REVIEW

File: Sources/Starknet/Data/TypedData/StarknetTypedData.swift [hunk 1]
```diff
@@ -397,34 +397,38 @@ public extension StarknetTypedData {
...
+        public init(from decoder: Decoder) throws {
+            let container = try decoder.singleValueContainer()
+            if let stringValue = try? container.decode(String.self), let value = Revision(rawValue: stringValue) {
+                self = value
+            } else if let intValue = try? container.decode(Int.self), let value = Revision(rawValue: String(intValue)) {
+                self = value
+            } else {
+                throw StarknetTypedDataError.decodingError
+            }
+        }
```
Comment (franciszekjob) [inline Sources/Starknet/Data/TypedData/StarknetTypedData.swift:431]: Here we consider int and string, because in rev 1, revision can be decoded both from string and int.

File: Tests/StarknetTests/Data/TypedDataTests.swift [hunk 2]
```diff
@@ -456,4 +456,22 @@ final class TypedDataTests: XCTestCase {
...
+            let td = try JSONDecoder().decode(StarknetTypedData.self, from: tdEncodedContents)
+            let tdEncoded = try JSONEncoder().encode(td)
+            let originalJson = try JSONSerialization.jsonObject(with: tdEncodedContents, options: []) as? [String: Any]
+            let encodedJson = try JSONSerialization.jsonObject(with: tdEncoded, options: []) as? [String: Any]
+            
+            XCTAssertEqual(originalJson as NSDictionary?, encodedJson as NSDictionary?)
+        } catch let e {
+            throw e
+        }
+    }
```
Comment (franciszekjob) [inline Tests/StarknetTests/Data/TypedDataTests.swift:476]: This test will be refactored in incoming PRs, also all of typed data test cases will be covered.

File: Tests/StarknetTests/Data/TypedDataTests.swift [hunk 3]
```diff
@@ -456,4 +456,22 @@ final class TypedDataTests: XCTestCase {
...
+            let td = try JSONDecoder().decode(StarknetTypedData.self, from: tdEncodedContents)
+            let tdEncoded = try JSONEncoder().encode(td)
+            let originalJson = try JSONSerialization.jsonObject(with: tdEncodedContents, options: []) as? [String: Any]
+            let encodedJson = try JSONSerialization.jsonObject(with: tdEncoded, options: []) as? [String: Any]
+
+            XCTAssertEqual(originalJson as NSDictionary?, encodedJson as NSDictionary?)
+        } catch let e {
+            throw e
+        }
+    }
```
Comment (franciszekjob) [inline Tests/StarknetTests/Data/TypedDataTests.swift:476]: Refactor + extending this tests will be covered in https://github.com/software-mansion/starknet.swift/issues/208

**Review by ddoktorski — APPROVED** [review]
