### PR TITLE
Fix encoding `version`  in typed data `Domain`

### LINKED ISSUE #227: TypedData `domain.version` is not encoded as short string
### What happened

`version` is encoded as `decimal` instead of `shortstring`

### Stack trace

No stack trace needed

### Steps to reproduce

1. Decode the following TypedData into `StarknetTypedData`
```
{
  "types": {
    "StarknetDomain": [
      {
        "name": "name",
        "type": "shortstring"
      },
      {
        "name": "version",
        "type": "shortstring"
      },
      {
        "name": "chainId",
        "type": "shortstring"
      },
      {
        "name": "revision",
        "type": "shortstring"
      }
    ],
    "OutsideExecution": [
      {
        "name": "Caller",
        "type": "ContractAddress"
      },
      {
        "name": "Nonce",
        "type": "felt"
      },
      {
        "name": "Execute After",
        "type": "u128"
      },
      {
        "name": "Execute Before",
        "type": "u128"
      },
      {
        "name": "Calls",
        "type": "Call*"
      }
    ],
    "Call": [
      {
        "name": "To",
        "type": "ContractAddress"
      },
      {
        "name": "Selector",
        "type": "selector"
      },
      {
        "name": "Calldata",
        "type": "felt*"
      }
    ]
  },
  "primaryType": "OutsideExecution",
  "domain": {
    "name": "Account.execute_from_outside",
    "version": "2",
    "chainId": "0x534e5f5345504f4c4941",
    "revision": "1"
  },
  "message": {
    "Caller": "0x75a180e18e56da1b1cae181c92a288f586f5fe22c18df21cf97886f1e4b316c",
    "Nonce": "0x29f08c9774aa8ef125944bfed79fa3e47f1327de4f0de2ea488e6a91587c9ed",
    "Execute After": "0x1",
    "Execute Before": "0x19642f34245",
    "Calls": [
      {
        "To": "0xabbd6f1e590eb83addd87ba5ac27960d859b1f17d11a3c1cd6a0006704b141",
        "Selector": "0x83afd3f4caedc6eebf44246fe54e38c95e3179a5ec9ea81740eca5b482d12e",
        "Calldata": [
          "0x783cfa7b667a36592c07156d0db751acaea3ee4bab0fd7cda6ea701bc7aae3c",
          "0x3b9aca00",
          "0x0"
        ]
      }
    ]
  }
}
```
2. Encode as JSON (note `"version": 2` instead of `"version": "2"`)
```
{
"types": {
      "StarknetDomain": [
        {
          "type": "shortstring",
          "name": "name"
        },
        {
          "type": "shortstring",
          "name": "version"
        },
        {
          "name": "chainId",
          "type": "shortstring"
        },
        {
          "type": "shortstring",
          "name": "revision"
        }
      ],
      "Call": [
        {
          "name": "To",
          "type": "ContractAddress"
        },
        {
          "name": "Selector",
          "type": "selector"
        },
        {
          "name": "Calldata",
          "type": "felt*"
        }
      ],
      "OutsideExecution": [
        {
          "name": "Caller",
          "type": "ContractAddress"
        },
        {
          "name": "Nonce",
          "type": "felt"
        },
        {
          "name": "Execute After",
          "type": "u128"
        },
        {
          "type": "u128",
          "name": "Execute Before"
        },
        {
          "name": "Calls",
          "type": "Call*"
        }
      ]
    },
    "domain": {
      "name": "Account.execute_from_outside",
      "revision": "1",
      "version": 2,
      "chainId": "0x534e5f5345504f4c4941"
    },
    "message": {
      "Caller": "0x75a180e18e56da1b1cae181c92a288f586f5fe22c18df21cf97886f1e4b316c",
      "Execute Before": "0x19642f34245",
      "Calls": [
        {
          "To": "0xabbd6f1e590eb83addd87ba5ac27960d859b1f17d11a3c1cd6a0006704b141",
          "Selector": "0x83afd3f4caedc6eebf44246fe54e38c95e3179a5ec9ea81740eca5b482d12e",
          "Calldata": [
            "0x783cfa7b667a36592c07156d0db751acaea3ee4bab0fd7cda6ea701bc7aae3c",
            "0x3b9aca00",
            "0x0"
          ]
        }
      ],
      "Execute After": "0x1",
      "Nonce": "0x29f08c9774aa8ef125944bfed79fa3e47f1327de4f0de2ea488e6a91587c9ed"
    }
}
```

### SDK Version

0.12.0

### Language version

5.0

### Is there an existing issue for this?

- [x] I have searched the existing issues and verified no issue exits for this problem.

### PR DESCRIPTION
**Pull request by franciszekjob**
## Describe your changes

`version` in `Domain` is now encoded as string, instead of number

## Linked issues

Closes #227 

## Breaking changes

- [ ] This issue contains breaking changes

### CODE REVIEW

File: Tests/StarknetTests/Data/TypedDataTests.swift [hunk 1]
```diff
@@ -47,14 +47,14 @@ final class TypedDataTests: XCTestCase {
...
-        "version": 1,
+        "version": "1",
         "chainId": 2137,
     }
     """
     static let exampleDomainV1 = """
     {
         "name": "DomainV1",
-        "version": 2,
+        "version": "2",
```
Comment (franciszekjob) [inline Tests/StarknetTests/Data/TypedDataTests.swift:57]: note: We wouldn't have to change this, but our tests compare original json and the one after decoding+encoding, hence it fails (version in original is int and in encoded it's string).

File: Sources/Starknet/Data/TypedData/StarknetTypedData.swift [hunk 2]
```diff
@@ -500,6 +518,21 @@ public extension StarknetTypedData {
...
+        case let .string(s): return s
+        case let .decimal(n): return String(n)
+        case let .signedDecimal(n): return String(n)
+        case let .felt(f): return f.toHex()
+        case let .signedFelt(f): return f.toHex()
+        case let .bool(b): return String(b)
+        default:
+            throw StarknetTypedDataError.encodingError
+        }
+    }
```
Comment (DelevoXDG) [inline Sources/Starknet/Data/TypedData/StarknetTypedData.swift:533]: That seems a bit Java-esque to me.

Shouldn't we instead be using [CustomStringConvertible](https://developer.apple.com/documentation/swift/customstringconvertible) conformance and overriding `description`?

That allows us to create string in a more swift-native way, via [`String(describing:)`](https://developer.apple.com/documentation/swift/string/init(describing:)-67ncf)

Comment (franciszekjob) [reply Sources/Starknet/Data/TypedData/StarknetTypedData.swift:533]: Valid suggestion

**Review by DelevoXDG — APPROVED** [review]
LGTM
