### PR TITLE
Fix types encoding in StarknetTypedData

### LINKED ISSUE #196: Bug in Starknet.swift v0.10.0: Incorrect Encoding of StarknetTypedData.types
### What happened

With the latest release of Starknet.swift v0.10.0, there is a bug in the encoding of `StarknetTypedData.types`. The changes have introduced an incorrect nested structure under the standard key, which deviates from the expected format.

```json
{
  "message": {
    "types": {
      "OutsideCall": [
        {
          "name": "to",
          "type": "felt"
        },
        {
          "name": "selector",
          "type": "felt"
        },
        {
          "name": "calldata_len",
          "type": "felt"
        },
        {
          "name": "calldata",
          "type": "felt*"
        }
      ]
    }
  }
}
```

With `v0.10.0`, the encoding now appears incorrectly as follows:

```json
{
  "message": {
    "types": {
      "OutsideCall": [
        {
          "standard": {
            "_0": {
              "type": "felt",
              "name": "to"
            }
          }
        },
        {
          "standard": {
            "_0": {
              "type": "felt",
              "name": "selector"
            }
          }
        },
        {
          "standard": {
            "_0": {
              "name": "calldata_len",
              "type": "felt"
            }
          }
        },
        {
          "standard": {
            "_0": {
              "name": "calldata",
              "type": "felt*"
            }
          }
        }
      ]
    }
  }
}
```

### Stack trace

Not related

### Steps to reproduce

1. Encode a message using Starknet.swift v0.10.0 with StarknetTypedData.
2. Observe the resulting JSON structure of types.

### SDK Version

v0.10.0

### Language version

5.9

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

### PR DESCRIPTION
**Pull request by franciszekjob**
## Describe your changes

- Add `TypeDeclarationWrapper.encode()` method to properly encode `types` in `StarknetTypedData`
## Linked issues

Closes #196 

## Breaking changes

- [ ] This issue contains breaking changes

### CODE REVIEW

File: Sources/Starknet/Data/TypedData/TypeDeclaration.swift [hunk 1]
```diff
@@ -98,5 +98,17 @@ public extension StarknetTypedData {
                 self = try .standard(StandardType(from: decoder))
             }
         }
+
+        public func encode(to encoder: Encoder) throws {
```
Comment (DelevoXDG) [inline Sources/Starknet/Data/TypedData/TypeDeclaration.swift:102]: Does this have to be public?

Comment (franciszekjob) [reply Sources/Starknet/Data/TypedData/TypeDeclaration.swift:102]: Yes because it matches a requirement in public protocol `Encodable`.
